// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvU0OXjql2gRaww3IVlYmooEzjkThaOZs',
    appId: '1:180343640958:web:210cfc85db9a7f63bd192f',
    messagingSenderId: '180343640958',
    projectId: 'hospital-app-5ec09',
    authDomain: 'hospital-app-5ec09.firebaseapp.com',
    storageBucket: 'hospital-app-5ec09.firebasestorage.app',
    measurementId: 'G-X6FQYPJDJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYoj3Jl4LPz-8sfcmmgV-MBom-OOLcFqE',
    appId: '1:180343640958:android:6823d05bc5a622cbbd192f',
    messagingSenderId: '180343640958',
    projectId: 'hospital-app-5ec09',
    storageBucket: 'hospital-app-5ec09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpip-swUoSgs6wLthG56CQ8Tnh2Oq9NM',
    appId: '1:180343640958:ios:40d7f23413babab1bd192f',
    messagingSenderId: '180343640958',
    projectId: 'hospital-app-5ec09',
    storageBucket: 'hospital-app-5ec09.firebasestorage.app',
    iosBundleId: 'com.example.hospitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtpip-swUoSgs6wLthG56CQ8Tnh2Oq9NM',
    appId: '1:180343640958:ios:40d7f23413babab1bd192f',
    messagingSenderId: '180343640958',
    projectId: 'hospital-app-5ec09',
    storageBucket: 'hospital-app-5ec09.firebasestorage.app',
    iosBundleId: 'com.example.hospitalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvU0OXjql2gRaww3IVlYmooEzjkThaOZs',
    appId: '1:180343640958:web:603f4b5034961147bd192f',
    messagingSenderId: '180343640958',
    projectId: 'hospital-app-5ec09',
    authDomain: 'hospital-app-5ec09.firebaseapp.com',
    storageBucket: 'hospital-app-5ec09.firebasestorage.app',
    measurementId: 'G-WGYCJ1102R',
  );
}
